2015-07-08 08:10:21,058 [16732] ERROR DefaultBootstrap - The process crashed for an unhandled exception!
System.TimeoutException: The sending attempt timed out
   在 SuperSocket.SocketBase.AppSession`2.InternalSend(ArraySegment`1 segment)
   在 SuperSocket.SocketBase.AppSession`2.Send(Byte[] data, Int32 offset, Int32 length)
   在 SuperSocket.SocketBase.AppSession`2.Send(String message)
   在 SuperSocket.SocketBase.AppSession`1.Send(String message)
   在 ESOP.Server.ESOPServer.OnStopped() 位置 d:\ESOPSolution\ESOP.Server\ESOPServer.cs:行号 40
   在 SuperSocket.SocketBase.AppServerBase`2.Stop()
   在 SuperSocket.SocketBase.AppServer`2.Stop()
   在 SuperSocket.SocketEngine.DefaultBootstrap.Stop()
   在 ESOP.Server.ServerManager.ServerManager_FormClosed(Object sender, FormClosedEventArgs e) 位置 d:\ESOPSolution\ESOP.Server\ServerManager.cs:行号 205
   在 System.Windows.Forms.Form.RaiseFormClosedOnAppExit()
   在 System.Windows.Forms.Application.ExitInternal()
   在 System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   在 System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   在 System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   在 System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   在 System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   在 ESOP.Server.Program.Main() 位置 d:\ESOPSolution\ESOP.Server\Program.cs:行号 19
